### ISSUE TITLE
Migrate "apollo-server-express" to 2.x

### ISSUE THREAD

**Issue by dimabory** [graphql-extended/gqlx-apollo-express-server#9]
A guide is available https://github.com/apollographql/apollo-server/blob/main/docs/source/migration-two-dot.md

**Comment by FlorianRappl** [comment]
That guide is not helpful because some functionality that we require (request specific context handling) is not there.

Otherwise the migration would have happened already. So somebody needs to look into the code how to achieve the same with the new version.

(Please have a look what glqx-apollo-express-server does; I recommend starting here: https://github.com/graphql-extended/gqlx-apollo-express-server/blob/master/src/configure.ts - this configures the middleware)

**Comment by FlorianRappl** [comment]
Landed in `0.5.0`. Thanks a lot for the superb contribution @dimabory !
